# Generated by Django 2.2.3 on 2019-07-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0005_auto_20190724_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
