# Generated by Django 2.2.3 on 2019-07-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/profile.jpg', null=True, upload_to='static/'),
        ),
    ]
