# Generated by Django 2.2.3 on 2019-07-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0011_auto_20190725_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
